const fs = require('fs');

const vbsLines = [
  "' YueXia Workbench - Dev Launcher (port 17328)",
  "",
  "Option Explicit",
  "",
  "Dim WshShell, FSO",
  "Dim ProjPath, Port, Url, NodeModulesPath",
  "Dim Cmd",
  "Dim VbsLogPath",
  "",
  "Set WshShell = CreateObject(\"WScript.Shell\")",
  "Set FSO = CreateObject(\"Scripting.FileSystemObject\")",
  "",
  "ProjPath = FSO.GetParentFolderName(WScript.ScriptFullName)",
  "Port     = 17328",
  "Url      = \"http://127.0.0.1:\" & Port & \"/#/dashboard\"",
  "NodeModulesPath = ProjPath & \"\\node_modules\"",
  "VbsLogPath = ProjPath & \"\\launcher\\vbs-launcher.log\"",
  "",
  "If Not FSO.FolderExists(ProjPath) Then",
  "    MsgBox \"Project folder not found:\" & vbCrLf & ProjPath, vbCritical, \"Error\"",
  "    WScript.Quit 1",
  "End If",
  "",
  "If Not FSO.FileExists(ProjPath & \"\\package.json\") Then",
  "    MsgBox \"package.json not found:\" & vbCrLf & ProjPath, vbCritical, \"Error\"",
  "    WScript.Quit 1",
  "End If",
  "",
  "If Not FSO.FolderExists(NodeModulesPath) Then",
  "    MsgBox \"Project dependencies are missing.\" & vbCrLf & vbCrLf & _",
  "           \"Please run the following in the project folder first:\" & vbCrLf & _",
  "           \"cmd /c npm install\" & vbCrLf & vbCrLf & _",
  "           \"Project path:\" & vbCrLf & ProjPath, vbCritical, \"Error\"",
  "    WScript.Quit 1",
  "End If",
  "",
  "On Error Resume Next",
  "Dim NodeVer",
  "NodeVer = WshShell.Exec(\"node --version\").StdOut.ReadLine()",
  "If Err.Number <> 0 Or NodeVer = \"\" Then",
  "    MsgBox \"Node.js not found! Please install Node.js\" & vbCrLf & \"https://nodejs.org\", vbCritical, \"Error\"",
  "    WScript.Quit 1",
  "End If",
  "On Error GoTo 0",
  "",
  "If IsPortReady(Port) Then",
  "    AppendLog VbsLogPath, \"Port ready, opening browser: \" & Url",
  "    OpenUrl Url",
  "    WScript.Quit 0",
  "End If",
  "",
  "Cmd = \"powershell -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File \"\"\" & ProjPath & \"\\launcher\\dev-launcher.ps1\"\"\"",
  "AppendLog VbsLogPath, \"Launching hidden PowerShell: \" & Cmd",
  "WshShell.Run Cmd, 0, False",
  "",
  "WScript.Quit 0",
  "",
  "Function IsPortReady(P)",
  "    On Error Resume Next",
  "    Dim Http",
  "    Set Http = CreateObject(\"MSXML2.ServerXMLHTTP.6.0\")",
  "    Http.setTimeouts 500, 500, 500, 500",
  "    Http.Open \"GET\", \"http://127.0.0.1:\" & P & \"/health\", False",
  "    Http.Send",
  "    IsPortReady = (Err.Number = 0 And Http.Status >= 200 And Http.Status < 400)",
  "    Set Http = Nothing",
  "    On Error GoTo 0",
  "End Function",
  "",
  "Sub OpenUrl(U)",
  "    On Error Resume Next",
  "    WshShell.Run \"explorer.exe \"\"\" & U & \"\"\"\", 1, False",
  "    If Err.Number <> 0 Then",
  "        WshShell.Run \"cmd /c start \"\"\" & U & \"\"\"\", 1, False",
  "    End If",
  "    On Error GoTo 0",
  "End Sub",
  "",
  "Sub AppendLog(LogPath, Msg)",
  "    On Error Resume Next",
  "    Dim File",
  "    Set File = FSO.OpenTextFile(LogPath, 8, True)",
  "    File.WriteLine Now & \" | \" & Msg",
  "    File.Close",
  "    Set File = Nothing",
  "    On Error GoTo 0",
  "End Sub",
];

const content = vbsLines.join('\r\n');
const bom = Buffer.from([0xEF, 0xBB, 0xBF]);
fs.writeFileSync('start-dev.vbs', Buffer.concat([bom, Buffer.from(content, 'utf8')]));
console.log('start-dev.vbs created successfully with UTF-8 BOM');
