const fs = require('fs');

const vbsLines = [
  "' 鏈堜笅鍐欎綔 - 寮€鍙戞ā寮忓惎鍔ㄥ櫒 (鐑洿鏂?+ 鑷姩鍒锋柊)",
  "' 鍙屽嚮鍚姩锛屽叧闂祻瑙堝櫒鍚庤嚜鍔ㄥ仠姝㈡湇鍔″櫒",
  "",
  "Option Explicit",
  "",
  "Dim WshShell, FSO",
  "Dim ProjPath, Port, Url",
  "Dim Cmd",
  "",
  "Set WshShell = CreateObject(\"WScript.Shell\")",
  "Set FSO = CreateObject(\"Scripting.FileSystemObject\")",
  "",
  "' 鑷姩鑾峰彇鏈?VBS 鏂囦欢鎵€鍦ㄧ洰褰曚綔涓洪」鐩矾寰?,
  "ProjPath = FSO.GetParentFolderName(WScript.ScriptFullName)",
  "Port     = 17328",
  "Url      = \"http://localhost:\" & Port",
  "",
  "If Not FSO.FolderExists(ProjPath) Then",
  "    MsgBox \"椤圭洰鏂囦欢澶逛笉瀛樺湪:\" & vbCrLf & ProjPath, vbCritical, \"閿欒\"",
  "    WScript.Quit 1",
  "End If",
  "",
  "If Not FSO.FileExists(ProjPath & \"\\package.json\") Then",
  "    MsgBox \"package.json 鏈壘鍒?\" & vbCrLf & ProjPath, vbCritical, \"閿欒\"",
  "    WScript.Quit 1",
  "End If",
  "",
  "On Error Resume Next",
  "Dim NodeVer",
  "NodeVer = WshShell.Exec(\"node --version\").StdOut.ReadLine()",
  "If Err.Number <> 0 Or NodeVer = \"\" Then",
  "    MsgBox \"鏈壘鍒?Node.js!\" & vbCrLf & vbCrLf & \"璇峰厛瀹夎 Node.js\" & vbCrLf & \"https://nodejs.org\", vbCritical, \"閿欒\"",
  "    WScript.Quit 1",
  "End If",
  "On Error GoTo 0",
  "",
  "' 妫€鏌ョ鍙ｆ槸鍚﹀凡琚崰鐢紙寮€鍙戞湇鍔″櫒鍙兘宸插湪杩愯锛?,
  "If IsPortReady(Port) Then",
  "    MsgBox \"绔彛 \" & Port & \" 宸茶鍗犵敤锛屽紑鍙戞湇鍔″櫒鍙兘宸插湪杩愯銆俓" & vbCrLf & vbCrLf & \"灏嗙洿鎺ユ墦寮€娴忚鍣ㄣ€俓", vbInformation, \"鎻愮ず\"",
  "    OpenUrl Url",
  "    WScript.Quit 0",
  "End If",
  "",
  "' 鍚姩寮€鍙戞ā寮忓惎鍔ㄥ櫒锛堣嚜鍔ㄦ娴嬫祻瑙堝櫒鍏抽棴骞跺仠鏈嶏級",
  "Cmd = \"cmd /c cd /d \"\"\" & ProjPath & \"\"\" && node launcher\\dev-launcher.cjs\"",
  "WshShell.Run Cmd, 1, False",
  "",
  "WScript.Quit 0",
  "",
  "' --------------------------------------------------",
  "Function IsPortReady(P)",
  "    On Error Resume Next",
  "    Dim Http",
  "    Set Http = CreateObject(\"MSXML2.XMLHTTP\")",
  "    Http.Open \"GET\", \"http://localhost:\" & P, False",
  "    Http.Send",
  "    IsPortReady = (Err.Number = 0 And Http.Status >= 200 And Http.Status < 400)",
  "    Set Http = Nothing",
  "    On Error GoTo 0",
  "End Function",
  "",
  "Sub OpenUrl(U)",
  "    On Error Resume Next",
  "    WshShell.Run \"explorer.exe \"\"\" & U & \"\"\"\", 1, False",
  "    If Err.Number <> 0 Then",
  "        WshShell.Run \"cmd /c start \"\"\" & U & \"\"\"\", 1, False",
  "    End If",
  "    On Error GoTo 0",
  "End Sub"
];

const content = vbsLines.join('\r\n');
const bom = Buffer.from([0xEF, 0xBB, 0xBF]);
fs.writeFileSync('start-dev.vbs', Buffer.concat([bom, Buffer.from(content, 'utf8')]));
console.log('start-dev.vbs created successfully with UTF-8 BOM');
